### ISSUE TITLE
Is the library in a usable/robust state?

### ISSUE THREAD

**Issue by mturnshek** [BeTomorrow/ReImproveJS#3]
If I wanted to train a feedforward network agent with ~100 inputs, 8 outputs, and a hidden layer of 512 or so, can I use a DQN from this library to do it and expect it to work out okay?

Does the DQN have any of the bells and whistles such as dueling DQN, prioritized experience replay, etc.?

**Comment by Pravez** [comment]
Hi,

Currently this library implements the "most simple" form of the DQN. It is absolutely possible to use it with your inputs/outputs/layers, but it will be only the Q function with only the classical experience replay. So It will work out okay but without wonderful results, because of the need of better algorithms. Double Learning et Prioritized Experience Replay will be implemented in the future, but it needs some time ;)

**Comment by mturnshek** [comment]
Thanks for the answer, keep up the good work!
